// src/react-renderer-front-end/react/src/Testimonial.js
import React from "react";
import ReactDOM from "react-dom";

const Testimonial = props => {
  ReactDOM.render(
    <div key={props.Id}>
      <h2>from React</h2>
      <p>{props.Quote}</p>
      <div>
        {props.ThumbnailUrl ? (
          <img width="50" height="50" src={props.ThumbnailUrl} alt="Test" />
        ) : null}
        <div>
          <h4>{props.Title}</h4>
          <b>{props.Company}</b>
        </div>
      </div>
    </div>,
    props.container
  )
}

export default Testimonial;

// src/angular-renderer-front-end/angular/src/app/testimonial.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Testimonial } from './testimonial';

@Component({
  selector: 'sf-testimonial',
  templateUrl: './testimonial.component.html',
  styles: []
})
export class TestimonialComponent implements OnInit {
  @Input()
  public model: string | undefined;

  public testimonial: Testimonial | undefined;
  ngOnInit() {
      if (this.model)
          this.testimonial = JSON.parse(this.model);
  }
}

<div *ngIf="testimonial">
  <p>{{testimonial.Quote}}</p>
  <div>
    <img *ngIf="testimonial.ThumbnailUrl" width="50" height="50" src={{testimonial.ThumbnailUrl}} alt="Test" />
    <div>
      <h4>{{testimonial.Title}}</h4>
      <b>{{testimonial.Company}}</b>
    </div>
  </div>
</div>
